CREATE DATABASE IF NOT EXISTS freebee
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE freebee;

DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS user_in_chat;
DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS role;


CREATE TABLE role(
	ROLE_ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE user(
	USER_ID INT PRIMARY KEY AUTO_INCREMENT,
	LOGIN VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ROLE_ID INT NOT NULL,
	UNIQUE(LOGIN),
	UNIQUE(EMAIL),
	FOREIGN KEY (ROLE_ID) REFERENCES role(ROLE_ID)
);

CREATE TABLE chat(
	CHAT_ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL
);

-- Описывает принадлежность пользователя к чату
CREATE TABLE user_in_chat(
    USER_IN_CHAT_ID INT PRIMARY KEY AUTO_INCREMENT,
    CHAT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    UNIQUE (CHAT_ID, USER_ID),
    FOREIGN KEY (CHAT_ID) REFERENCES chat(CHAT_ID),
    FOREIGN KEY (USER_ID) REFERENCES user(USER_ID)
);

CREATE TABLE message(
	MESSAGE_ID INT PRIMARY KEY AUTO_INCREMENT,
	USER_IN_CHAT_ID INT NOT NULL,
	SEND_TIME DATETIME NOT NULL,
	MESS_TEXT TEXT NOT NULL,
	INDEX `LAST_MESS` (USER_IN_CHAT_ID, SEND_TIME),
	FOREIGN KEY (USER_IN_CHAT_ID) REFERENCES user_in_chat(USER_IN_CHAT_ID)
);
