USE freebee;
ALTER TABLE user ADD COLUMN ENABLE BOOL DEFAULT TRUE;
ALTER TABLE chat ADD COLUMN ENABLE BOOL DEFAULT TRUE;
ALTER TABLE user_in_chat ADD COLUMN ENABLE BOOL DEFAULT TRUE;
ALTER TABLE message ADD COLUMN ENABLE BOOL DEFAULT TRUE;
